apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: REALM_APPLICATION
data:
  databasePassword: {{ .Values.databasePassword | b64enc | quote }}
  replicaDatabasePassword: {{ .Values.replicaDatabasePassword | b64enc | quote }}
  key.json: {{ .Values.keyJson | b64enc | quote }}
  REALM_APPLICATION-bigquery-sa.json: {{ .Values.REALM_APPLICATIONBigquerySa | b64enc | quote }}
